### ISSUE TITLE
An example of serialising an Expression Tree

### ISSUE THREAD

**Issue by BlueFin605** [6bee/Remote.Linq-Samples#1]
I have been playing with your remote.linq library to see if I can use it to serialise an Expression Tree, which your sample Remote.Linq.Newtonsoft.Json appears to do, but I cannot figure out how to actually execute the lambda.

I want my app to build up a bunch of expressions and persist them somewhere and be able to retrieve them and execute them.  So there is actually no database providing the data source, just an expression that takes a parameter(s) to produce output.

If this is actually something your library can do, can you please add a sample app demonstrating it.  I was trying to use the Microsoft sample Expression

`// Add the following using directive to your code file:  
// using System.Linq.Expressions;  
  
// Manually build the expression tree for   
// the lambda expression num => num < 5.  
ParameterExpression numParam = Expression.Parameter(typeof(int), "num");  
ConstantExpression five = Expression.Constant(5, typeof(int));  
BinaryExpression numLessThanFive = Expression.LessThan(numParam, five);  
Expression<Func<int, bool>> lambda1 =  
    Expression.Lambda<Func<int, bool>>(  
        numLessThanFive,  
        new ParameterExpression[] { numParam });`

**Comment by 6bee** [comment]
Yes, you should be able to utilize remote.linq in your scenario. 
Just use the extension methods `ToRemoteLinqExpression` and `ToLinqExpression` to convert between `System.Linq.Expressions.Expression` and `Remote.Linq.Expressions.Expression`. 

Then, either cast into the correct type: 
```
var remoteLinqExpression = lambda1.ToRemoteLinqExpression();
// persist / load 
var expression = (Expression<Func<int, bool>>)remoteLinqExpression.ToLinqExpression();
var lambda = expression.Compile();
var x4 = lambda(4);
var x5 = lambda(5);
```

Or use the dynamic keyword: 
```
var remoteLinqExpression = lambda1.ToRemoteLinqExpression();
// persist / load 
var expression = remoteLinqExpression.ToLinqExpression();
dynamic lambda = expression.Compile();
var x4 = lambda.Invoke(4);
var x5 = lambda.Invoke(5);
```
